name: CI Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run pre-commit hooks
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pip install poetry
        poetry install
        poetry run pytest
